"""Machine-readable metadata for configuration options under compatibility review."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass(frozen=True)
class ConfigOption:
    """Describe one public configuration option and its support status."""

    env_name: str
    yaml_path: str
    default: str
    validator: str
    description: str
    status: Literal["active", "deprecated"] = "active"
    replacement: str | None = None


CONFIG_OPTIONS: tuple[ConfigOption, ...] = (
    ConfigOption(
        env_name="WEB_UI_REFRESH_INTERVAL_SECONDS",
        yaml_path="web_ui.refresh_interval_seconds",
        default="5",
        validator="integer >= 1",
        description="Polling interval of the overview page in seconds.",
    ),
    ConfigOption(
        env_name="OBS_HEARTBEAT_INTERVAL_SECONDS",
        yaml_path="observability.heartbeat_interval_seconds",
        default="30",
        validator="deprecated; value is ignored",
        description="Reserved option that never controlled a runtime heartbeat.",
        status="deprecated",
        replacement="Use the health endpoints and SMARTTUB_POLLING_INTERVAL_SECONDS.",
    ),
    ConfigOption(
        env_name="OBS_TELEMETRY_BATCH_SIZE",
        yaml_path="observability.telemetry_batch_size",
        default="10",
        validator="deprecated; value is ignored",
        description="Reserved option that never controlled telemetry batching.",
        status="deprecated",
        replacement="No replacement; MQTT state publishing is not batch based.",
    ),
    ConfigOption(
        env_name="SAFETY_FAIL_SAFE_MODE",
        yaml_path="safety.fail_safe_mode",
        default="stop_pumps",
        validator="deprecated; value is ignored",
        description="Never activated an automatic fail-safe action.",
        status="deprecated",
        replacement="No replacement; the bridge does not issue unrequested commands.",
    ),
    ConfigOption(
        env_name="SAFETY_POST_COMMAND_WAIT_SECONDS",
        yaml_path="safety.post_command_wait_seconds",
        default="12",
        validator="deprecated; value is ignored",
        description="Never controlled the command state refresh delay.",
        status="deprecated",
        replacement="Use STATE_UPDATE_DELAY_SECONDS.",
    ),
    ConfigOption(
        env_name="SAFETY_COMMAND_VERIFICATION_RETRIES",
        yaml_path="safety.command_verification_retries",
        default="3",
        validator="deprecated; value is ignored",
        description="Never enabled command verification retries.",
        status="deprecated",
        replacement="No replacement; inspect the command result and observed state.",
    ),
    ConfigOption(
        env_name="SAFETY_COMMAND_MAX_RETRIES",
        yaml_path="safety.command_max_retries",
        default="2",
        validator="deprecated; value is ignored",
        description="Never controlled command retries.",
        status="deprecated",
        replacement="No replacement; commands are not retried automatically.",
    ),
    ConfigOption(
        env_name="DISCOVERY_REFRESH_INTERVAL",
        yaml_path="capability.discovery_refresh_interval",
        default="3600",
        validator="deprecated; value is ignored",
        description="Never scheduled periodic invasive discovery.",
        status="deprecated",
        replacement="Use DISCOVERY_MODE for startup discovery or start it manually.",
    ),
    ConfigOption(
        env_name="CAPABILITY_ENABLE_AUTO_DISCOVERY",
        yaml_path="capability.enable_auto_discovery",
        default="true",
        validator="deprecated; value is ignored",
        description="Never enabled automatic discovery.",
        status="deprecated",
        replacement="Use DISCOVERY_MODE=off|startup_quick|startup_full|startup_yaml.",
    ),
)


DEPRECATED_BY_ENV = {
    option.env_name: option
    for option in CONFIG_OPTIONS
    if option.status == "deprecated"
}
DEPRECATED_BY_YAML = {
    option.yaml_path: option
    for option in CONFIG_OPTIONS
    if option.status == "deprecated"
}


def render_reviewed_configuration_reference() -> str:
    """Render the checked-in reference from the registry."""
    lines = [
        "<!-- Generated by scripts/generate_config_reference.py; do not edit. -->",
        "# Reviewed configuration options",
        "",
        "This reference covers the options audited in project-analysis item P1-02.",
        "Deprecated options are accepted for one compatibility cycle, emit a warning,",
        "and have no runtime effect.",
        "",
        "| Environment | YAML path | Default | Validation | Status | Description / migration |",
        "|---|---|---:|---|---|---|",
    ]
    for option in CONFIG_OPTIONS:
        details = option.description
        if option.replacement:
            details = f"{details} {option.replacement}"
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{option.env_name}`",
                    f"`{option.yaml_path}`",
                    f"`{option.default}`",
                    option.validator,
                    option.status,
                    details,
                )
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)
